# Numpy Exercises
The objective of numpy is homogeneous data array. Numpy is much faster than other traditional approaches for mathematical operations such as math library, list etc. The reason for numpy to be fast is that it stored all the data in memory buffer and all data have same type that's why don't need to chech data type and don't to call data because all data is in memory buffer.

In [1]:
import numpy as np

<b>1. Write a Python program to print the NumPy version in your system.<b>

In [2]:
print(np.__version__)

1.15.0


<b>2. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. <b>

In [3]:
a = [12.23, 13.32, 100, 36.32]
type(a)

list

In [4]:
a = np.array(a)
type(a)

numpy.ndarray

In [5]:
print(a)

[ 12.23  13.32 100.    36.32]


<b>3. Create a 3x3 matrix with values ranging from 2 to 10.<b>

In [6]:
a = np.arange(2, 11).reshape(3, 3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


<b>4. Write a Python program to create a null vector of size 10 and update sixth value to 11.<b>

In [7]:
null_verctor = np.zeros((10,))
null_verctor.size

10

In [8]:
null_verctor[6] = 11
print(null_verctor)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


<b>5. Write a Python program to create an array with values ranging from 12 to 38.<b>

In [9]:
a = np.arange(12, 38)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


<b>6. Write a Python program to reverse an array (first element becomes last).<b>

In [10]:
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [11]:
reverse_a = a[-1::-1]
print(reverse_a)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


<b>7. Write a Python program to an array converted to a float type<b>

In [12]:
int_array = np.array([1, 2, 3, 4])
print(int_array.dtype)

int32


In [13]:
float_array = np.array(int_array, dtype='float32')
print(float_array.dtype)

float32


In [14]:
print(float_array)

[1. 2. 3. 4.]


<b>8. Write a Python program to create a 2d array with 1 on the border and 0 inside.<b>

In [15]:
array_2d = np.ones(shape=[10, 10], dtype='int')
print(array_2d)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [16]:
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


`<b>9. Write a Python program to add a border (filled with 0's) around an existing array.<b>

In [17]:
array_1 = np.ones((4, 4), dtype='int')
print(array_1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
array_2 = np.zeros((6, 6), dtype='int')
print(array_2)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [19]:
array_2[1:-1, 1:-1] = array_1
array_1 = array_2

In [20]:
print(array_1)

[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


<b>10. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.<b>

In [21]:
x = np.zeros((8, 8), dtype='int')

In [22]:
print("Checkerboard pattern:")
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


<b>11. Write a Python program to convert a list and tuple into arrays.<br>
List to array:<br>
[1 2 3 4 5 6 7 8]<br> 
Tuple to array:<br>
[[8 4 6] <br>
[1 2 3]]<b>

In [23]:
list_ = [1, 2, 3, 4, 5, 6, 7, 8]
tuple_ = ((8, 4, 6), (1, 2, 3))

In [24]:
list_ = np.array(list_)
tuple_ = np.array(tuple_)

In [25]:
print(list_)

[1 2 3 4 5 6 7 8]


In [26]:
print(tuple_)

[[8 4 6]
 [1 2 3]]


<b>12. Write a Python program to append values to the end of an array.<br>
Expected Output:<br>
Original array:<br>
[10, 20, 30] <br>
After append values to the end of the array:<br>
[10 20 30 40 50 60 70 80 90]<b>

In [27]:
array = np.array([10, 20, 30])
array = np.append(array, [40, 50, 60, 70, 80, 90])
print(array)

[10 20 30 40 50 60 70 80 90]


<b>13. Write a Python program to create an empty and a full array.<br>
Expected Output:<br>
[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]<br>
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310] <br>
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]] <br>
[[6 6 6]<br>
[6 6 6] <br>
[6 6 6]] <b>

In [28]:
empty_array = np.empty(shape=(3, 3))
print(empty_array)

[[0.00000000e+000 3.08296963e-321 2.47032823e-323]
 [2.14375427e-312 0.00000000e+000 2.47032823e-323]
 [2.14375435e-312 0.00000000e+000 3.56040677e-307]]


In [29]:
full_array = np.full(shape=(3, 3), fill_value=6)
print(full_array)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


<b>14. Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.<br>
Sample Array [0, 12, 45.21 ,34, 99.91]<br>
Expected Output:<br>
Values in Fahrenheit degrees:<br>
[ 0. 12. 45.21 34. 99.91] <br>
Values in Centigrade degrees: <br>
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778] <b>

In [30]:
centigrade = np.array([0, 12, 45.21, 34, 99.91])

In [31]:
fahrenheit = centigrade*9/5 + 32
print(fahrenheit)

[ 32.     53.6   113.378  93.2   211.838]


<b>15. Write a Python program to find the real and imaginary parts of an array of complex numbers.<br>
Expected Output:<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j] <br>
Real part of the array: <br>
[ 1. 0.70710678] <br>
Imaginary part of the array:<br>
[ 0. 0.70710678] <b>

In [32]:
original_array = np.array([1.00000000+0.j, 0.70710678+0.70710678j], dtype='complex')

In [33]:
print(original_array.real)

[1.         0.70710678]


In [34]:
print(original_array.imag)

[0.         0.70710678]


<b>16. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.<br>
Expected Output:<br>
Size of the array: 3<br>
Length of one array element in bytes: 8 <br>
Total bytes consumed by the elements of the array: 24<b>

In [35]:
array = np.array([1, 2, 3], dtype='float64')
size = array.size
print('Size of the array: ', size)

Size of the array:  3


In [36]:
byte_size = array.itemsize
print('Length of one array element: ', byte_size)

Length of one array element:  8


In [37]:
print('Total bytes consumed by the elements of the array: ', size*byte_size)

Total bytes consumed by the elements of the array:  24


<b>17. Write a Python program to test whether each element of a 1-D array is also present in a second array.<br>
Expected Output:<br>
Array1: [ 0 10 20 40 60]<br>
Array2: [0, 40] <b>

In [38]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])

In [39]:
np.in1d(array1, array2)

array([ True, False, False,  True, False])

<b>18. Write a Python program to find common values between two arrays.<br>
Expected Output:<br>
Array1: [ 0 10 20 40 60] <br>
Array2: [10, 30, 40]<br>
Common values between two arrays:<br>
[10 40] <b>

In [40]:
array1 = np.array([0, 10, 20, 40, 60]) 
array2 = np.array([10, 30, 40])

In [41]:
index = np.in1d(array1, array2)
print(array1[index])

[10 40]


<b>19. Write a Python program to get the unique elements of an array.<br>
Expected Output:<br>
Original array:<br>
[10 10 20 20 30 30]<br> 
Unique elements of the above array:<br>
[10 20 30] <br>
Original array:<br>
[[1 1]<br> 
[2 3]]<br>
Unique elements of the above array:<br>
[1 2 3] <b>

In [42]:
a = np.array([10, 10, 20, 20, 30, 30])
np.unique(a)

array([10, 20, 30])

<b>20. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.<br>
Expected Output:<br>
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70, 90]<br> 
Set difference between two arrays:<br>
[ 0 20 60 80]<b>

In [43]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

In [44]:
np.setdiff1d(array1, array2)

array([ 0, 20, 60, 80])

<b>21. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.<br>
Array1: [ 0 10 20 40 60 80] <br>
Array2: [10, 30, 40, 50, 70] <br>
Unique values that are in only one (not both) of the input arrays: <br>
[ 0 20 30 50 60 70 80]<br>
<b>

In [45]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

In [46]:
np.setxor1d(array1, array2)

array([ 0, 20, 30, 50, 60, 70, 80, 90])

<b>22. Write a Python program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.<br>
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70]<br>
Unique sorted array of values that are in either of the two input arrays:<br>
[ 0 10 20 30 40 50 60 70 80]<b>

In [47]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

In [48]:
np.union1d(array1, array2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

<b>23. Write a Python program to test if all elements in an array evaluate to True. Go to the editor
Note: 0 evaluates to False in python.<b>